platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 2.0'
pod 'SwiftDate'
pod 'FontAwesomeKit', '~> 2.1.0'
pod 'SVProgressHUD'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
pod 'RESideMenu', '~> 4.0.4'
pod 'SDWebImage', '~>3.7'

pod 'Google-Mobile-Ads-SDK'
#pod 'ReachabilitySwift'

pod 'Fabric'
pod 'Crashlytics'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBAudienceNetwork'